### ISSUE TITLE
Issues with Android 8/8.1

### ISSUE THREAD

**Issue by felipecds** [iamthevoid/media-picker-android#1]
First of all, thanks a lot for your library, it's helping me a lot.

On my initial tests with android 8/8.1, I'm having two issues.

1. I'm using the Ressurrection Remix Oreo ROM on Moto G4 Plus, and tested with two different camera apps. Only when I capture the camera's picture, it isn't starting the crop activity, and because this it isn't propagating the events to observers.

2. On my Moto Z2 Play, using stock Oreo 8.0.0, the image that is showing on crop activity have a poor quality, compared with the image on gallery.

On logcat, no errors are showing. 

Where can I get some logs to help finding the issue?

**Comment by iamthevoid** [comment]
@felipecds Hello, thanks a lot for your comment and issue! I newbee in android and it is too cool that my libs attract some attention )) 

Bad thing is the I haven't add any logger to this project. I could do something with it, but i not sure than it will going so fast. During the week if the best happened. 

And i will try to solve your problem too.

If you could you may download the project, check it with debugger and make pull request, if you will fix you case. 

At the moment I have no idea why you got case #1, but case #2 is looks like you haven't add fileprovider to your project (by the way #1 case looks like it too, check it please). For API 21 and above (if i remember it correctly) you must provide fileprovider to store photo file at you device. If you haven't you will get case when image from camera come back in intent and will have too poor quality. Instead it fileprovider helps to store full size image in storage and returns path in intent. Example is in test app, you can try it. 

Please reply whether it helps or not.

Sorry for my bad english by the way )

Best regards!

**Comment by iamthevoid** [comment]
Just started to debug this. Looks like i can reproduce this bug. I'll update lib soon, just wait a little. Thanks

**Comment by iamthevoid** [comment]
@felipecds I've upload hotfix 0.2.3 version, please check

**Comment by felipecds** [comment]
@iamthevoid Thnks for replying, and sorry for my late response (so much work kkk).

About the file provider, I'm already added it to my project (something I do by default in all my projects), and the issues are just on oreo, so that was a strange sittuation. 

I was about to download the repo and try to debug when I read your answer. Updating my project with v  0.2.3 and it worked like a charm!!!

Thank you so much.

**Comment by iamthevoid** [comment]
@felipecds there is nothing strange. Google team just increase stability and break down my intent nullability check. There was null Intent in onActivityResult, but became empty ))

**Comment by felipecds** [comment]
I see, but anyway, some Google changes are unpredictable but I'm glad that could be solved.
